### PR TITLE
fix lookat implementation

### LINKED ISSUE #62: eye and center swapped in lookat
if a camera is situated in point **e**, we want to render in the frame (**e**, x',y',z') and not (c, x',y',z') as stated here:
https://github.com/ssloy/tinyrenderer/wiki/Lesson-5-Moving-the-camera#let-us-create-our-own-glulookat

As an aftereffect you move to `-center` instead of `-eye` as gluLookAt would do:
https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/gluLookAt.xml

But I want to say that this is a really cool and useful lecture that you have put together.

I came up with a similar idea to warm my students up with python and opencv. However, I stopped at flat-shading and thus things are far less impressive - but thats at about 10 lines of python/ opencv:
https://www.rojtberg.net/1709/fast-wire-frame-rendering-with-opencv/

### LINKED ISSUE #67: sign error in zbuffer
the camera is looking along -Z, which means the smaller Z, the closer to the camera (in World coords).
The sign get flipped in the projection matrix here:
https://github.com/ssloy/tinyrenderer/blob/d5355f5d23b5bb3ca82eb7c02702c870f5fc1c29/main.cpp#L71

now the larger Z, the farther away from the camera the coordinate is.

you initialise the zbuffer like:
https://github.com/ssloy/tinyrenderer/blob/d5355f5d23b5bb3ca82eb7c02702c870f5fc1c29/main.cpp#L67

However, zbuffer should be initialised with `max()` instead of `-max()`.

Indeed, a typical OpenGL zbuffer looks like

instead of

### PR DESCRIPTION
**Pull request by paroj**
fixes #67
fixes #62

### CODE REVIEW

**Review by ssloy — COMMENTED** [review]
this pull request modifies the final render image; the result does not seem correct

**Comment by paroj** [comment]
> this pull request modifies the final render image; the result does not seem correct

hows that? All this does is some renaming (note the swapped function arguments). 

While on its own this is arguable not useful, it should highlight the inconsistencies in the existing code (e.g. the direction of the z vector).

**Comment by paroj** [comment]
before:
framebuffer

after:
framebuffer2

**Comment by ssloy** [comment]
Dear Pavel, thank you very much for your dedication! I have no time right now to check your code, but I will do as soon as I can drop my current tasks, I am very interested, do not be frustrated by my lack of communication.

**Comment by paroj** [comment]
no worries. totally understand that. 

Also there is still some sign error somewhere, which I had to cover up by inverting the vertex winding.

**Comment by paroj** [comment]
done. images match now.

**Comment by paroj** [comment]
the last commit is optional and up to taste, but it makes the "shader" code resemble GLSL more

File: main.cpp [hunk 1]
```diff
@@ -16,21 +16,21 @@ extern mat<4,4> Projection;
 
 struct Shader : IShader {
     const Model &model;
-    vec3 l;               // light direction in normalized device coordinates
+    vec3 l;               // light direction in view coordinates
```
Comment (dvorontsov) [inline main.cpp]: I am curious, was there a reason why the lighting was originally done in NDC?  From what I understand, it can also be done in World or View coordinates, as long as we stay consistent, right?

Sorry, I am not really commenting on the change, I am trying to understand the motivation for choosing one frame or reference over another.

**Review by ssloy — APPROVED** [review]

File: our_gl.cpp [hunk 2]
```diff
@@ -14,11 +14,11 @@ void projection(const double coeff) { // check https://github.com/ssloy/tinyrend
 }
 
 void lookat(const vec3 eye, const vec3 center, const vec3 up) { // check https://github.com/ssloy/tinyrenderer/wiki/Lesson-5-Moving-the-camera
-    vec3 z = (eye-center).normalize();
+    vec3 z = (center-eye).normalize();
```
[the remark this answers is not in the document]
Comment (Buzzefall) [reply our_gl.cpp:17]: I confirm that this change may be a mistake, on my implementation it's (eye-center). I beared in mind conventions **x+** is right, **y+** is up, **z+** is looking into my face (opposite direction of camera view). But my overall code differs, can't say 100% sure.

File: our_gl.cpp [hunk 3]
```diff
@@ -14,11 +14,11 @@ void projection(const double coeff) { // check https://github.com/ssloy/tinyrend
...
     vec3 x =  cross(up,z).normalize();
     vec3 y =  cross(z, x).normalize();
     mat<4,4> Minv = {{{x.x,x.y,x.z,0},   {y.x,y.y,y.z,0},   {z.x,z.y,z.z,0},   {0,0,0,1}}};
-    mat<4,4> Tr   = {{{1,0,0,-center.x}, {0,1,0,-center.y}, {0,0,1,-center.z}, {0,0,0,1}}};
+    mat<4,4> Tr   = {{{1,0,0,-eye.x}, {0,1,0,-eye.y}, {0,0,1,-eye.z}, {0,0,0,1}}};
```
Comment (Buzzefall) [inline our_gl.cpp:21]: This fox should be correct. Drived me mad to find one :)
